{{- $fullName := include "greenmail.fullname" . -}}
{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-{{ .service }}"
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .service }}
  selector:
{{- end }}
{{- end }}